export const config: {
  SUBGRAPH_URL: string;
  INFURA_KEY: string;
  NETWORK: string;
  TLBC_JSON_RPC_URL: string;
  RELAY_URL: string;
  FIREBASE_API_KEY: string;
  FIREBASE_AUTH_DOMAIN: string;
  FIREBASE_DATABASE_URL: string;
  FIREBASE_PROJECT_ID: string;
  FIREBASE_STORAGE_BUCKET: string;
  FIREBASE_MESSAGINGSENDER_ID: string,
  FIREBASE_APP_ID: string;
  FIREBASE_MEASUREMENT_ID: string;
} = {
  SUBGRAPH_URL: process.env.REACT_APP_SUBGRAPH_URL || "",
  INFURA_KEY: process.env.REACT_APP_INFURA_KEY || "",
  NETWORK: process.env.REACT_APP_NETWORK || "",
  TLBC_JSON_RPC_URL: process.env.REACT_APP_TLBC_JSON_RPC_URL || "",
  RELAY_URL: process.env.REACT_APP_RELAY_URL || "",
  FIREBASE_API_KEY: process.env.REACT_APP_FIREBASE_API_KEY || "",
  FIREBASE_AUTH_DOMAIN: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN || "",
  FIREBASE_DATABASE_URL: process.env.REACT_APP_FIREBASE_DATABASE_URL || "",
  FIREBASE_PROJECT_ID: process.env.REACT_APP_FIREBASE_PROJECT_ID || "",
  FIREBASE_STORAGE_BUCKET: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET || "",
  FIREBASE_MESSAGINGSENDER_ID: process.env.REACT_APP_FIREBASE_MESSAGINGSENDER_ID || "",
  FIREBASE_APP_ID: process.env.REACT_APP_FIREBASE_APP_ID || "",
  FIREBASE_MEASUREMENT_ID: process.env.REACT_APP_FIREBASE_MEASUREMENT_ID || ""
};

export const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000"

export default config;
